javac -encoding "utf-8" -sourcepath src -d classes src/part_one/task_one/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_one/task_two/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_one/task_three/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_one/task_four/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_two/task_one/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_two/task_two/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_two/task_three/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_two/task_four/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_three/task_one/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_three/task_two/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_three/task_three/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_three/task_four/*.java
javac -encoding "utf-8" -sourcepath src -d classes src/part_three/task_four/server/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_three/task_four/client/*
javac -encoding "utf-8" -sourcepath src -d classes src/part_three/task_five/*.java
javac -encoding "utf-8" -sourcepath src -d classes src/part_three/task_five/client/*.java
javac -encoding "utf-8" -sourcepath src -d classes src/part_three/task_five/server/*.java
javac -encoding "utf-8" -sourcepath src -d classes src/part_three/task_five/interfaces/*.java
javac -encoding "utf-8" -sourcepath src -d classes src/part_three/task_five/functions/*.java
javac -encoding "utf-8" -sourcepath src -d classes src/part_four/task_one/*.java
javac -encoding "utf-8" -sourcepath src -d classes src/part_four/task_two/*.java
javac -encoding "utf-8" -sourcepath src -d classes src/part_four/task_three/*.java
pause